[build-system]
requires = [
    "ninja",
    "packaging",
    "setuptools",
    "torch @ https://download.pytorch.org/whl/nightly/cu121/torch-2.1.0.dev20230904+cu121-cp310-cp310-linux_x86_64.whl",
    "wheel",
]
build-backend = "setuptools.build_meta"
